model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    ckpt_path: "/work/pi_hzhang2_umass_edu/oyoungquist_umass_edu/taming-transformers/logs/2023-11-08T15-08-00_custom_vqgan/checkpoints/last.ckpt"
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 3
    num_workers: 8
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: /work/pi_hzhang2_umass_edu/oyoungquist_umass_edu/datasets/V2X-Sim/positive_vali_v2x.txt
        size: 256
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: /work/pi_hzhang2_umass_edu/oyoungquist_umass_edu/datasets/DeepAccident/negative_test_deep_acc_eval.txt
        size: 256

